### ISSUE TITLE
Highly optimized and very tiny bezier script

### ISSUE THREAD

**Issue by dalisoft** [gre/bezier-easing#12]
```javascript
function Bezier(mX1, mX2, mY1, mY2) {
  var isLinear = mX1 === mY1 && mX2 === mY2;
  return function (aX) {
   return (isLinear || aX === 0 || aX === 1) ? aX : (((1.0 - 3.0 * mY2 + 3.0 * mY1) * aX + (3.0 * mY2 - 6.0 * mY1)) * aX + (3.0 * mY1)) * aX;
  }
 }
// copyright (c) 2015 @dalisoft. All right reserved
```

**Comment by dalisoft** [comment]
This is a optimized and clean version

**Comment by gre** [comment]
I don't think your code is equivalent to bezier-easing one's.

As I understand your code, you are implementing the bezier formula which gives a Y for a given percentage but that is not enough to know the Y of a given X. because bezier percentage does not means x position.
There is not any (known) way to get the Y position of the X projection to the bezier curve other than doing a dichotomic search (Firefox and Chrome both uses this technique and bezier-easing implementation is inspired from it).

> bezier-easing implement the CSS' cubic-easing as shown in this schema:
![](https://camo.githubusercontent.com/114770b7314af59c3ca07eda80addb9e672f756f/687474703a2f2f7777772e77332e6f72672f54522f637373332d7472616e736974696f6e732f54696d696e6746756e6374696f6e2e706e67)


For instance, with your function:

```
Bezier(0, 0, 0, 1)(0.5)
````
returns `0.5` where it should returns approximatively `0.89` as shown in this schema:

![screen shot 2015-06-20 at 22 36 37](https://cloud.githubusercontent.com/assets/211411/8269135/5b3c67e2-179d-11e5-904a-65a49ec95c0b.png)



I hope this is clear.

Best regards

**Comment by dalisoft** [comment]
Thanks for reply
